<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>name</key>
  <string>Modula-3</string>
  <key>fileTypes</key>
  <array>
    <string>m3</string>
    <string>mg</string>
    <string>i3</string>
    <string>ig</string>
  </array>
  <key>patterns</key>
  <array>
    <dict>
      <key>name</key>
      <string>keyword.modula-3</string>
      <key>match</key>
      <string>\b(ANY|ARRAY|AS|BEGIN|BITS|BRANDED|BY|CASE|CONST|DO|ELSE|ELSIF|END|EVAL|EXCEPT|EXCEPTION|EXIT|EXPORTS|FINALLY|FOR|FROM|GENERIC|IF|IMPORT|INTERFACE|LOCK|LOOP|METHODS|MODULE|OBJECT|OF|OVERRIDES|PROCEDURE|RAISE|RAISES|READONLY|RECORD|REF|REPEAT|RETURN|REVEAL|ROOT|SET|THEN|TO|TRY|TYPE|TYPECASE|UNSAFE|UNTIL|UNTRACED|VALUE|VAR|WHILE|WITH)\b</string>
    </dict>
    <dict>
      <key>name</key>
      <string>keyword.operator.modula-3</string>
      <key>match</key>
      <string>\b(AND|DIV|IN|MOD|NOT|OR)\b</string>
    </dict>
    <dict>
      <key>name</key>
      <string>constant.language.modula-3</string>
      <key>match</key>
      <string>\b(FALSE|NIL|ROOT|TRUE)\b</string>
    </dict>
    <dict>
      <key>name</key>
      <string>constant.numeric.float.modula-3</string>
      <key>match</key>
      <string>(\b|[\+\-])[0-9]+\.[0-9]+([DdEeXx][\+\-]?[0-9]+)?\b</string>
    </dict>
    <dict>
      <key>name</key>
      <string>constant.numeric.integer.modula-3</string>
      <key>match</key>
      <string>(\b|[\+\-])[0-9]+(\_[0-9a-fA-F]+)?L?\b</string>
    </dict>
    <dict>
      <key>name</key>
      <string>comment.block.modula-3</string>
      <key>begin</key>
      <string>\(\*</string>
      <key>end</key>
      <string>\*\)</string>
    </dict>
    <dict>
      <key>name</key>
      <string>keyword.control.directive.pragma.modula-3</string>
      <key>begin</key>
      <string>\&lt;\*</string>
      <key>end</key>
      <string>\*\&gt;</string>
    </dict>
    <dict>
      <key>name</key>
      <string>string.quoted.double.modula-3</string>
      <key>begin</key>
      <string>"</string>
      <key>end</key>
      <string>"</string>
      <key>patterns</key>
      <array>
        <dict>
          <key>name</key>
          <string>constant.character.escape.modula-3</string>
          <key>match</key>
          <string>\\[0-7]{3}|\\[\\fnrt\"\']</string>
        </dict>
      </array>
    </dict>
    <dict>
      <key>name</key>
      <string>string.quoted.single.modula-3</string>
      <key>begin</key>
      <string>'</string>
      <key>end</key>
      <string>'</string>
      <key>patterns</key>
      <array>
        <dict>
          <key>name</key>
          <string>constant.character.escape.modula-3</string>
          <key>match</key>
          <string>\\[0-7]{3}|\\[\\fnrt\"\']</string>
        </dict>
      </array>
    </dict>
  </array>
  <key>scopeName</key>
  <string>source.modula-3</string>
  <key>uuid</key>
  <string>4c94bed0-63b5-43a2-b2be-d777f02a0a95</string>
</dict>
</plist>
